### ISSUE TITLE
Slow or absent payment confirmations

### ISSUE THREAD

**Issue by justinclagg** [brainblocks/brainblocks#29]
To provide some data on payment confirmations, I made three payment attempts through the web wallet which all followed the same pattern:

1. Payment received (pending) instantly
2. Payment pocketed after about 60 seconds
3. Timer runs out without confirmation, and payment is later refunded

**Comment by justinclagg** [comment]
Here are the three refunded transactions:

633634897F4A076C61ACCABA696F6EF98EFA1E414C386962B7C4964F8E13210A
64B7A97FD8D11485F8D2CBD1FA4EF35318A062D878BF0612CDD9ACF61F7E6DBC
08416784E6BF3DEACDCD3739136DCD7E6D82243F08EFE7955DAE079F5E45E407

I also had one successful transaction, but it might have timed with the end of the timer close enough that I wasn't able to submit my order:

7968F4AE3D4A6E0F3CF9ABF0D37EDA06C821C673EBF85AC112BC1386CB951138

Hope that helps!

**Comment by bluepnume** [comment]
I think I see the problem here:

633634897F4A076C61ACCABA696F6EF98EFA1E414C386962B7C4964F8E13210A

This transaction is showing up in the database as $10.95 USD === 0.586106. You sent 0.586000 -- since this was slightly under, the transaction didn't go through and you were auto-refunded.

But, this is our fault, since the button only shows 3 decimal places. So really good catch. I'll get a fix in for this!

**Comment by bluepnume** [comment]
OK, this should be fixed -- can you please try again and let me know any transaction ids which show problems? For now I've capped usd -> rai conversion to 3 decimal places, which ends up being about 1.5 cents. That should be enough for now.

Thanks again for the report!
