### ISSUE TITLE
Getting error: Incorrect destination 

### ISSUE THREAD

**Issue by shawkath1238** [brainblocks/brainblocks#40]
Hello,
I am using wordpress and woocommerce for my e-commerce site. Installed BrainBlocks for woocommerce and filled everything its aseked but getting this following error: 

Incorrect destination: expected xrb_1h6whxmojzr5m3ezkrzbf4n8fukp6k33o6uit5gteroi3kha5eg8p1rxbp98

Any suggestion why ??
![brainblocks](https://user-images.githubusercontent.com/36567409/36341996-8caeb0ec-13f7-11e8-906b-ca3a82db39bb.PNG)

**Comment by bluepnume** [comment]
Do you have a url where I can repro the problem? Thanks!

**Comment by shawkath1238** [comment]
This is my site: 
kryptocafe.de but I am sure this is not what you looking right ?

**Comment by schenkty** [comment]
@shawkath1238 Do you have a test page with brainblocks enabled? Does not look enabled on your main site. Thanks, Ty

**Comment by bluepnume** [comment]
FYI, I've uploaded a new version of this plugin, which includes an option (enabled by default) to do a full-page redirect rather than showing the brainblocks button inline. Would appreciate if you can try this instead if you're still seeing problems, as it should resolve some compatibility issues.

https://brainblocks.io/static/woocommerce-gateway-brainblocks.zip

<img width="771" alt="screen shot 2018-03-11 at 2 46 09 pm" src="https://user-images.githubusercontent.com/1219075/37258846-24668280-253b-11e8-987d-957b6d1f87d3.png">

**Comment by shawkath1238** [comment]
Hi, thank you, everyone. It's working now.
