### ISSUE TITLE
Place Order Checkout Button Not Showing on Some Browsers

### ISSUE THREAD

**Issue by TristenBlack** [brainblocks/brainblocks#45]
After the new WooCommerce update ( i believe 3.3.2) the checkout button no longer shows on some browsers. I haven't tested them all but it doesn't seem to be working with Safari, Iphones. Not only can you not checkout with Nano but the button is not there for any checkout. When I disable the plugin it shows again. So it is currently disabled.

**Comment by bluepnume** [comment]
FYI, I've uploaded a new version of this plugin, which includes an option (enabled by default) to do a full-page redirect rather than showing the brainblocks button inline. Would appreciate if you can try this instead if you're still seeing problems, as it should resolve some compatibility issues.

https://brainblocks.io/static/woocommerce-gateway-brainblocks.zip

<img width="771" alt="screen shot 2018-03-11 at 2 46 09 pm" src="https://user-images.githubusercontent.com/1219075/37258846-24668280-253b-11e8-987d-957b6d1f87d3.png">

**Comment by schenkty** [comment]
This is no longer relevant with the latest WooCommerce plugin version
