### ISSUE TITLE
Shopify checkout is sending NANO to wrong wallet.

### ISSUE THREAD

**Issue by therichardla** [brainblocks/brainblocks#49]
I got an order from a customer who bought a t-shirt and it remains unpaid on my shopify store and checked to see if it was deposited into my wallet, it wasn't.  So i did a test order and the address when i tested it out is different from my personal wallet.  I use nanovault btw.  I wonder if that is an issue?

**Comment by therichardla** [comment]
for what it's worth, my shopify store is www.satoshiswear.com

**Comment by bluepnume** [comment]
Can you share the address for some of these payments?

**Comment by therichardla** [comment]
xrb_3we7erbtnzhrsjg4qcqpw4nccqs453r9xx4x5k1ymuwkujsy4rg1p15k1b51

this is my nano address.  the one that shows up on the script in my shopify.  but at checkout screen, its a different addresss

**Comment by bluepnume** [comment]
Yes, BrainBlocks generates an intermediary nano address, so it can validate the payment has been made before sending the funds to your final address.

I see four transactions with your final address:

```
            created            |                             account                              | amount 
-------------------------------+------------------------------------------------------------------+--------
 2018-03-04 18:00:43.167034+00 | xrb_114qffjraiohcbf1etw3k4my1cg7ncnrbddhhoc7co3koj995o9ckndnt9x3 | 37.18
 2018-03-04 21:43:00.323555+00 | xrb_1pbikc68dx7r7hi1x79ddqychprbzjuekp6dsfunmsohbzeokwa5ar4b6pax | 26.45
 2018-03-05 02:51:50.555723+00 | xrb_1g6njdj4pskd4nejhum79j9r514ikw8tgqzqziaj7oekhazj9o15u5jbbpdy | 26.45
 2018-03-05 03:47:06.200227+00 | xrb_3pkwbymsak3ia5wkyzya6snhi5si3mnpsumnb7dgmb9jryfdunmnk8mzpqgc | 30.00
```

But I don't see any payments to any of these accounts when I look them up in nanode, for example: https://www.nanode.co/account/xrb_1pbikc68dx7r7hi1x79ddqychprbzjuekp6dsfunmsohbzeokwa5ar4b6pax

Was any nano actually paid by your customer to any of the address that BrainBlocks displayed to them? And in which case, which address?

I'm guessing this is because the current shopify integration creates the order then shows the BrainBlocks button on the final page. So the buyer might actually decide not to pay. In this case, I think we can probably assume they abandoned the order.

(+ @Vindexus to make sure my understanding is correct for the shopify plugin)

**Comment by therichardla** [comment]
Alright, thank you.  Just didnt want a customer to have sent Nano and I not fulfill the order in a timely manner.  Appreciate the answer.

**Comment by bluepnume** [comment]
No problem. We have plans to improve this shortly, and make sure the order is cancelled if the payment doesn't happen. Thanks for the report!
